export {default as Home} from './Home/Home'
export {default as Profile} from './Profile/Profile'
export{default as Search} from './Search/Search'
export {default as Notification} from './Notification/Notification'
export {default as Post} from './Post/Post'