export default{
    intro: require('../assets/images/ic_1.png'),
    login: require('../assets/images/ic_main_logo.png'),
    apple:require('../assets/images/ic_apple.png'),
    facebook: require('../assets/images/ic_facebook.png'),
    google : require('../assets/images/ic_google.png'),
    arrow :require('../assets/images/ic_back_arrow.png'),
    down_arrow: require('../assets/images/ic_down.png'),
    Home:require('../assets/images/ic_home.png'),
    Notify:require('../assets/images/ic_notify.png'),
    search:require('../assets/images/ic_srch.png'),
    post:require('../assets/images/ic_plus.png'),
    profile:require('../assets/images/ic_user.png'),
    redPlus:require('../assets/images/ic_red_add.png'),
    loc:require('../assets/images/ic_loc.png'),
    logo:require('../assets/images/ic_home_icon.png'),
    Profile:require('../assets/images/images(1).jpeg'),
    dot:require('../assets/images/ic_dots.png'),
    post1:require('../assets/images/download.jpeg'),
    ForwardImage:require('../assets/images/ic_direction.png'),
    SignOut:require('../assets/images/ic_logout.png'),
    ChangePassword:require('../assets/images/ic_key.png'),
    Edit:require('../assets/images/ic_edit.png')
}